### ISSUE TITLE
WASM format support

### ISSUE THREAD

**Issue by silgon** [dlemstra/Magick.Native#42]
I know that there is not support for svg to png, since there is no `inkscape` in the browser and for other formats there is the `gs` also that is not available. However, can you clarify for the format `HEIC`? It seems that it can read but not write in `wasm`, is it normal or it might be a bug?
![image](https://github.com/dlemstra/Magick.Native/assets/901061/d1aaca35-f166-4b96-89c9-64e104d4ff03)

Thanks!

**Comment by dlemstra** [comment]
There is only support for writing `AVIF` images due to license issues. The encoder that is used to write `HEIC` images is not compatible with our license.

You can convert from svg to png by using the `readFromCanvas` method and then save it as a PNG file. That is also the reason there was no svg support added because the browser already has proper support for it. And if you are using node in a terminal you should use inkscape directly instead.

And support for Ghostscript was also not added because of licensing issues. But in theory it should be possible to add binaries to the file system of the library and then use it. But I have not had or made time to check if I could get that working.

**Comment by silgon** [comment]
Thank you for your reply. I understand. BTW, pretty nice project you have created @dlemstra 😀
